version: '3'
services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  backend:
    build:
      dockerfile: Dockerfile
      context: ./central-academy-backend
    env_file:
      - backend.env
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./central-academy-client
    env_file:
      - frontend.env
